name: Run Star Wars API Tests

on:
  push:
    branches:  main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Newman
      run: npm install -g newman

    - name: Run Star Wars Collection
      run: |
        newman run starwars_api_tests.postman_collection.json \
          --reporters cli
